version: '3.8'
services:
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_URI: mongodb+srv://juan:juan@cluster0.keids.mongodb.net/
    ports:
      - '4000:4000'
    depends_on:
      - database
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: juan
      MONGO_INITDB_ROOT_PASSWORD: juan